version: "3.8"

networks:
  docker:
    driver: bridge

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - docker
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db:/var/lib/mysql
    container_name: db

  app:
    build: docker/php-fpm
    volumes:
      - ./symfony:/var/www/html/app
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - docker
    environment:
      PHP_IDE_CONFIG: "serverName=App"
    container_name: app

  nginx:
    image: nginx:1.23
    volumes:
      - ./symfony:/var/www/html/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - docker
    ports:
      - "80:80"
    container_name: nginx

  memcached:
    image: memcached:1.6.18
    networks:
      - docker
    ports:
      - '11211:11211'
    container_name: memcached

